import { BUTTON_TITLE } from '../contents';

export const TAGS_TEXT = {
  itm: BUTTON_TITLE.INTRODUCTION_TO_MEDICINE,
  cmo: BUTTON_TITLE.CLINICAL_MEDICINE_OVERVIEW,
  bmi: BUTTON_TITLE.BIOMEDICAL_MEASUREMENT_INSTRUMENTATION,
  mte: BUTTON_TITLE.MEDICAL_THERAPEUTIC_EQUIPMENT,
  mds: BUTTON_TITLE.MED_DEV_SAFETY,
  meee: BUTTON_TITLE.MEDICAL_ELECTRICAL_AND_ELECTRONIC_ENGINEERING,
  bfse: BUTTON_TITLE.BIOLOGICAL_FUNCTION_SUBSTITUTION_EQUIPMENT,
  mme: BUTTON_TITLE.MEDICAL_MECHANICAL_ENGINEERING,
  bmse: BUTTON_TITLE.BIOLOGICAL_MATERIAL_SCIENCE_AND_ENGINEERING,
};
